# Generated by Django 2.0.3 on 2018-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180322_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='repository',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='metadataPrefix',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
