# Generated by Django 2.0.3 on 2018-04-03 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_harvester_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvester', to=settings.AUTH_USER_MODEL),
        ),
    ]
