# Generated by Django 2.0.3 on 2018-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180403_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
