# Generated by Django 2.0.3 on 2018-04-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180425_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvester',
            options={'ordering': ['name']},
        ),
    ]
