__author__ = "Jan Frömberg"
__copyright__ = "Copyright 2018, GeRDI Project"
__credits__ = ["Jan Frömberg"]
__license__ = "Apache"
__version__ = "1.0.0"
__maintainer__ = "Jan Frömberg"
__email__ = "Jan.froemberg@tu-dresden.de"

class Harvester_API:
    P_HARVEST="/harvest"
    P_HARVEST_ABORT="/harvest/abort"
    P_HARVEST_SUBMIT="/harvest/submit"
    P_HARVEST_SAVE="/harvest/save"
    P_HARVEST_CRON="/harvest/schedule?cron="
    G_HARVEST_CRON="/harvest/schedule"
    G_STATUS="/harvest/status/state"
    G_HEALTH="/harvest/status/health"
    G_PROGRESS="/harvest/status/progress"
    G_MAX_DOCS="/harvest/status/max-documents"
    G_DATA_PROVIDER="/harvest/status/data-provider"
    G_HARVESTED_DOCS="/harvest/status/harvested-documents"
    G_BOOLEAN_OUTDATED_DOCS="/harvest/outdated"
    D_HARVEST_CRON="/harvest/schedule?cron="
    D_HARVEST_CRONS="/harvest/schedule"
